<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Detangle.Rendering</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Markdig" />
    <PackageReference Include="Mermaider" />
    <PackageReference Include="TextMateSharp" />
    <PackageReference Include="TextMateSharp.Grammars" />
    <PackageReference Include="Svg.Controls.Skia.Avalonia" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Detangle.Core\Detangle.Core.csproj" />
  </ItemGroup>

</Project>
