<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Detangle.Core.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Detangle.Core\Detangle.Core.csproj" />
    <ProjectReference Include="..\..\src\Detangle.Lint\Detangle.Lint.csproj" />
  </ItemGroup>

</Project>
